import Header from "@/components/shared/header/Header";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import Footer from "@/components/shared/footer/Footer";
import QueryProvider from "@/providers/QueryProvider";

import ScrollTop from "@/components/shared/ScrollTop";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: "300",
});

export const metadata = {
  title: "ECYBD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />

        <div className="pt-[69px] lg:pt-[72px] xl:pt-[88px]">
          <QueryProvider>{children}</QueryProvider>
        </div>
        <ScrollTop />
        <Footer />
      </body>
    </html>
  );
}
